function define<K extends keyof WindowEventMap>(name: K, transform: (e: WindowEventMap[K]) => any) {
    return {
        name,
        transform
    }
}

function mouse_event(e: MouseEvent) {
    return {
        ...base_event(e),
        altKey: e.altKey,
        button: e.button,
        buttons: e.buttons,
        clientX: e.clientX,
        clientY: e.clientY,
        ctrlKey: e.ctrlKey,
        layerX: e.layerX,
        layerY: e.layerY,
        metaKey: e.metaKey,
        movementX: e.movementX,
        movementY: e.movementY,
        offsetX: e.offsetX,
        offsetY: e.offsetY,
        pageX: e.pageX,
        pageY: e.pageY,
        screenX: e.screenX,
        screenY: e.screenY,
        shiftKey: e.shiftKey,
        x: e.x,
        y: e.y,
    }
}

function keyboard_event(e: KeyboardEvent) {
    return {
        ...base_event(e),
        altKey: e.altKey,
        code: e.code,
        ctrlKey: e.ctrlKey,
        key: e.key,
        location: e.location,
        metaKey: e.metaKey,
        repeat: e.repeat,
        shiftKey: e.shiftKey,
        which: e.which,
    }
}

function base_event(e: Event) {
    return {
        value: (e.target as any).value
    }
}

export default {
    'on_click': define('click', mouse_event),
    "on_abort": define('abort', base_event),
    "on_afterprint": define('afterprint', base_event),
    "on_beforeprint": define('beforeprint', base_event),
    "on_beforeunload": define('beforeunload', base_event),
    "on_blur": define('blur', base_event),
    "on_canplay": define("canplay", base_event),
    "on_canplaythrough": define("canplaythrough", base_event),
    "on_change": define("change", base_event),
    "on_compassneedscalibration": define("compassneedscalibration", base_event),
    "on_contextmenu": define("contextmenu", base_event),
    "on_dblclick": define("dblclick", base_event),
    "on_devicelight": define("devicelight", base_event),
    "on_devicemotion": define("devicemotion", base_event),
    "on_deviceorientation": define("deviceorientation", base_event),
    "on_drag": define("drag", base_event),
    "on_dragend": define("dragend", base_event),
    "on_dragenter": define("dragenter", base_event),
    "on_dragleave": define("dragleave", base_event),
    "on_dragover": define("dragover", base_event),
    "on_dragstart": define("dragstart", base_event),
    "on_drop": define("drop", base_event),
    "on_durationchange": define("durationchange", base_event),
    "on_emptied": define("emptied", base_event),
    "on_ended": define("ended", base_event),
    "on_error": define("error", base_event),
    "on_focus": define("focus", base_event),
    "on_hashchange": define("hashchange", base_event),
    "on_input": define("input", base_event),
    "on_invalid": define("invalid", base_event),
    "on_keydown": define("keydown", keyboard_event),
    "on_keypress": define("keypress", keyboard_event),
    "on_keyup": define("keyup", keyboard_event),
    "on_load": define("load", base_event),
    "on_loadeddata": define("loadeddata", base_event),
    "on_loadedmetadata": define("loadedmetadata", base_event),
    "on_loadstart": define("loadstart", base_event),
    "on_message": define("message", base_event),
    "on_mousedown": define("mousedown", mouse_event),
    "on_mouseenter": define("mouseenter", mouse_event),
    "on_mouseleave": define("mouseleave", mouse_event),
    "on_mousemove": define("mousemove", mouse_event),
    "on_mouseout": define("mouseout", mouse_event),
    "on_mouseover": define("mouseover", mouse_event),
    "on_mouseup": define("mouseup", mouse_event),
    "on_mousewheel": define("mousewheel", mouse_event),
    "on_MSGestureChange": define("MSGestureChange", base_event),
    "on_MSGestureDoubleTap": define("MSGestureDoubleTap", base_event),
    "on_MSGestureEnd": define("MSGestureEnd", base_event),
    "on_MSGestureHold": define("MSGestureHold", base_event),
    "on_MSGestureStart": define("MSGestureStart", base_event),
    "on_MSGestureTap": define("MSGestureTap", base_event),
    "on_MSInertiaStart": define("MSInertiaStart", base_event),
    "on_MSPointerCancel": define("MSPointerCancel", base_event),
    "on_MSPointerDown": define("MSPointerDown", base_event),
    "on_MSPointerEnter": define("MSPointerEnter", base_event),
    "on_MSPointerLeave": define("MSPointerLeave", base_event),
    "on_MSPointerMove": define("MSPointerMove", base_event),
    "on_MSPointerOut": define("MSPointerOut", base_event),
    "on_MSPointerOver": define("MSPointerOver", base_event),
    "on_MSPointerUp": define("MSPointerUp", base_event),
    "on_offline": define("offline", base_event),
    "on_online": define("online", base_event),
    "on_orientationchange": define("orientationchange", base_event),
    "on_pagehide": define("pagehide", base_event),
    "on_pageshow": define("pageshow", base_event),
    "on_pause": define("pause", base_event),
    "on_play": define("play", base_event),
    "on_playing": define("playing", base_event),
    "on_popstate": define("popstate", base_event),
    "on_progress": define("progress", base_event),
    "on_ratechange": define("ratechange", base_event),
    "on_readystatechange": define("readystatechange", base_event),
    "on_reset": define("reset", base_event),
    "on_resize": define("resize", base_event),
    "on_scroll": define("scroll", base_event),
    "on_seeked": define("seeked", base_event),
    "on_seeking": define("seeking", base_event),
    "on_select": define("select", base_event),
    "on_stalled": define("stalled", base_event),
    "on_storage": define("storage", base_event),
    "on_submit": define("submit", base_event),
    "on_suspend": define("suspend", base_event),
    "on_timeupdate": define("timeupdate", base_event),
    "on_unload": define("unload", base_event),
    "on_volumechange": define("volumechange", base_event),
    "on_vrdisplayactivate": define("vrdisplayactivate", base_event),
    "on_vrdisplayblur": define("vrdisplayblur", base_event),
    "on_vrdisplayconnect": define("vrdisplayconnect", base_event),
    "on_vrdisplaydeactivate": define("vrdisplaydeactivate", base_event),
    "on_vrdisplaydisconnect": define("vrdisplaydisconnect", base_event),
    "on_vrdisplayfocus": define("vrdisplayfocus", base_event),
    "on_vrdisplaypointerrestricted": define("vrdisplaypointerrestricted", base_event),
    "on_vrdisplaypointerunrestricted": define("vrdisplaypointerunrestricted", base_event),
    "on_vrdisplaypresentchange": define("vrdisplaypresentchange", base_event),
    "on_waiting": define("waiting", base_event),
} 